name: 'Deploy Quarkus QE Test Framework'
description: 'Deploys Quarkus QE Test Framework'
inputs:
  repository-id:
    description: 'Must match a repository id present in of the POM file distributionManagement repositories'
    required: true
  release-version:
    description: 'Version under which should this framework be released'
  ossrh-username:
    required: true
  ossrh-token:
    required: true
  gpg-passphrase:
    required: true
  gpg-private-key:
    required: true
runs:
  using: "composite"
  steps:
    - name: Install JDK 17
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: 17
        check-latest: true
        server-id: ${{ inputs.repository-id }}
        server-username: MAVEN_USERNAME
        server-password: MAVEN_PASSWORD
        gpg-private-key: ${{ inputs.gpg-private-key }}
        gpg-passphrase: MAVEN_GPG_PASSPHRASE
    - name: Set Quarkus QE Test Framework version to ${{ inputs.release-version }}
      shell: bash
      run: mvn -B versions:set -DnewVersion=$NEW_FRAMEWORK_VERSION
      env:
        NEW_FRAMEWORK_VERSION: ${{ inputs.release-version }}
    - name: Maven deploy ${{ inputs.release-version }}
      shell: bash
      run: |
        mvn -B -DskipTests -DskipITs \
          -DretryFailedDeploymentCount=3 \
          -Pdeploy,framework \
          -Drelease=$RELEASE \
          clean deploy
      env:
        MAVEN_USERNAME: ${{ inputs.ossrh-username }}
        MAVEN_PASSWORD: ${{ inputs.ossrh-token }}
        MAVEN_GPG_PASSPHRASE: ${{ inputs.gpg-passphrase }}
        RELEASE: ${{ ! endsWith(inputs.release-version, 'SNAPSHOT') }}
    - name: Delete Local Artifacts From Cache
      shell: bash
      run: rm -r ~/.m2/repository/io/quarkus/qe